// Copyright (c) 2019-2025 Five Squared Interactive. All rights reserved.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace FiveSQD.WebVerse.Handlers.VEML.Schema.V2_3
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3", IsNullable=false)]
    public partial class veml {
        
        private vemlMetadata metadataField;
        
        private vemlEnvironment environmentField;
        
        /// <remarks/>
        public vemlMetadata metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        public vemlEnvironment environment {
            get {
                return this.environmentField;
            }
            set {
                this.environmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class vemlMetadata {
        
        private string titleField;
        
        private string[] capabilityField;
        
        private string[] scriptField;
        
        private inputevent[] inputeventField;
        
        private controlflags controlflagsField;
        
        private synchronizationservice[] synchronizationserviceField;
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("capability")]
        public string[] capability {
            get {
                return this.capabilityField;
            }
            set {
                this.capabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("script")]
        public string[] script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inputevent")]
        public inputevent[] inputevent {
            get {
                return this.inputeventField;
            }
            set {
                this.inputeventField = value;
            }
        }
        
        /// <remarks/>
        public controlflags controlflags {
            get {
                return this.controlflagsField;
            }
            set {
                this.controlflagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("synchronizationservice")]
        public synchronizationservice[] synchronizationservice {
            get {
                return this.synchronizationserviceField;
            }
            set {
                this.synchronizationserviceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class inputevent {
        
        private string inputField;
        
        private string eventField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class terrainentitylayer {
        
        private string diffusetextureField;
        
        private string normaltextureField;
        
        private string masktextureField;
        
        private string specularField;
        
        private float metallicField;
        
        private float smoothnessField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("diffuse-texture")]
        public string diffusetexture {
            get {
                return this.diffusetextureField;
            }
            set {
                this.diffusetextureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("normal-texture")]
        public string normaltexture {
            get {
                return this.normaltextureField;
            }
            set {
                this.normaltextureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mask-texture")]
        public string masktexture {
            get {
                return this.masktextureField;
            }
            set {
                this.masktextureField = value;
            }
        }
        
        /// <remarks/>
        public string specular {
            get {
                return this.specularField;
            }
            set {
                this.specularField = value;
            }
        }
        
        /// <remarks/>
        public float metallic {
            get {
                return this.metallicField;
            }
            set {
                this.metallicField = value;
            }
        }
        
        /// <remarks/>
        public float smoothness {
            get {
                return this.smoothnessField;
            }
            set {
                this.smoothnessField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class placementsocket {
        
        private position positionField;
        
        private rotation rotationField;
        
        private position connectingoffsetField;
        
        /// <remarks/>
        public position position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public rotation rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("connecting-offset")]
        public position connectingoffset {
            get {
                return this.connectingoffsetField;
            }
            set {
                this.connectingoffsetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class position {
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        public position() {
            this.xField = 0D;
            this.yField = 0D;
            this.zField = 0D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class rotation {
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        private double wField;
        
        public rotation() {
            this.xField = 0D;
            this.yField = 0D;
            this.zField = 0D;
            this.wField = 1D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double w {
            get {
                return this.wField;
            }
            set {
                this.wField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="size-percent", Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class sizepercent {
        
        private double xField;
        
        private double yField;
        
        public sizepercent() {
            this.xField = 1D;
            this.yField = 1D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="position-percent", Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class positionpercent {
        
        private double xField;
        
        private double yField;
        
        public positionpercent() {
            this.xField = 0D;
            this.yField = 0D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class size {
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        public size() {
            this.xField = 1D;
            this.yField = 1D;
            this.zField = 1D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class scale {
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        public scale() {
            this.xField = 1D;
            this.yField = 1D;
            this.zField = 1D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(canvastransform))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sizetransform))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(scaletransform))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class basetransform {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class canvastransform : basetransform {
        
        private positionpercent positionpercentField;
        
        private sizepercent sizepercentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("position-percent")]
        public positionpercent positionpercent {
            get {
                return this.positionpercentField;
            }
            set {
                this.positionpercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("size-percent")]
        public sizepercent sizepercent {
            get {
                return this.sizepercentField;
            }
            set {
                this.sizepercentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class sizetransform : basetransform {
        
        private position positionField;
        
        private rotation rotationField;
        
        private size sizeField;
        
        /// <remarks/>
        public position position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public rotation rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
            }
        }
        
        /// <remarks/>
        public size size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class scaletransform : basetransform {
        
        private position positionField;
        
        private rotation rotationField;
        
        private scale scaleField;
        
        /// <remarks/>
        public position position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public rotation rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
            }
        }
        
        /// <remarks/>
        public scale scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(waterblockerentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(waterentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(voxelentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(textentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(terrainentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lightentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(imageentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(inputentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(buttonentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(htmlentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(canvasentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(characterentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(archmeshentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(prismmeshentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tetrahedronmeshentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(rectangularpyramidmeshentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(conemeshentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(torusmeshentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(planemeshentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cylindermeshentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(capsulemeshentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(spheremeshentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cubemeshentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(meshentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(audioentity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(containerentity))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class entity {
        
        private basetransform transformField;
        
        private entity[] entity1Field;
        
        private string synchronizerField;
        
        private placementsocket[] placementsocketField;
        
        private string tagField;
        
        private string idField;
        
        private string onloadeventField;
        
        /// <remarks/>
        public basetransform transform {
            get {
                return this.transformField;
            }
            set {
                this.transformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entity")]
        public entity[] entity1 {
            get {
                return this.entity1Field;
            }
            set {
                this.entity1Field = value;
            }
        }
        
        /// <remarks/>
        public string synchronizer {
            get {
                return this.synchronizerField;
            }
            set {
                this.synchronizerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("placement-socket")]
        public placementsocket[] placementsocket {
            get {
                return this.placementsocketField;
            }
            set {
                this.placementsocketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("on-load-event")]
        public string onloadevent {
            get {
                return this.onloadeventField;
            }
            set {
                this.onloadeventField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class waterblockerentity : entity {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class waterentity : entity {
        
        private string shallowcolorField;
        
        private string deepcolorField;
        
        private string specularcolorField;
        
        private string scatteringcolorField;
        
        private float deepstartField;
        
        private float deependField;
        
        private float distortionField;
        
        private float smoothnessField;
        
        private float numwavesField;
        
        private float waveamplitudeField;
        
        private float wavesteepnessField;
        
        private float wavespeedField;
        
        private float wavelengthField;
        
        private float wavescaleField;
        
        private float waveintensityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shallow-color")]
        public string shallowcolor {
            get {
                return this.shallowcolorField;
            }
            set {
                this.shallowcolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deep-color")]
        public string deepcolor {
            get {
                return this.deepcolorField;
            }
            set {
                this.deepcolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("specular-color")]
        public string specularcolor {
            get {
                return this.specularcolorField;
            }
            set {
                this.specularcolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scattering-color")]
        public string scatteringcolor {
            get {
                return this.scatteringcolorField;
            }
            set {
                this.scatteringcolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deep-start")]
        public float deepstart {
            get {
                return this.deepstartField;
            }
            set {
                this.deepstartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deep-end")]
        public float deepend {
            get {
                return this.deependField;
            }
            set {
                this.deependField = value;
            }
        }
        
        /// <remarks/>
        public float distortion {
            get {
                return this.distortionField;
            }
            set {
                this.distortionField = value;
            }
        }
        
        /// <remarks/>
        public float smoothness {
            get {
                return this.smoothnessField;
            }
            set {
                this.smoothnessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("num-waves")]
        public float numwaves {
            get {
                return this.numwavesField;
            }
            set {
                this.numwavesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wave-amplitude")]
        public float waveamplitude {
            get {
                return this.waveamplitudeField;
            }
            set {
                this.waveamplitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wave-steepness")]
        public float wavesteepness {
            get {
                return this.wavesteepnessField;
            }
            set {
                this.wavesteepnessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wave-speed")]
        public float wavespeed {
            get {
                return this.wavespeedField;
            }
            set {
                this.wavespeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wave-length")]
        public float wavelength {
            get {
                return this.wavelengthField;
            }
            set {
                this.wavelengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wave-scale")]
        public float wavescale {
            get {
                return this.wavescaleField;
            }
            set {
                this.wavescaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wave-intensity")]
        public float waveintensity {
            get {
                return this.waveintensityField;
            }
            set {
                this.waveintensityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class voxelentity : entity {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class textentity : entity {
        
        private string textField;
        
        private float fontsizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("font-size")]
        public float fontsize {
            get {
                return this.fontsizeField;
            }
            set {
                this.fontsizeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class terrainentity : entity {
        
        private terrainentitylayer[] layerField;
        
        private string layermasksField;
        
        private double lengthField;
        
        private double widthField;
        
        private double heightField;
        
        private string heightsField;
        
        private string typeField;
        
        public terrainentity() {
            this.typeField = "heightmap";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("layer")]
        public terrainentitylayer[] layer {
            get {
                return this.layerField;
            }
            set {
                this.layerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("layer-masks")]
        public string layermasks {
            get {
                return this.layermasksField;
            }
            set {
                this.layermasksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string heights {
            get {
                return this.heightsField;
            }
            set {
                this.heightsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("heightmap")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class lightentity : entity {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class imageentity : entity {
        
        private string imagefileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("image-file")]
        public string imagefile {
            get {
                return this.imagefileField;
            }
            set {
                this.imagefileField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class inputentity : entity {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class buttonentity : entity {
        
        private string onclickeventField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("on-click-event")]
        public string onclickevent {
            get {
                return this.onclickeventField;
            }
            set {
                this.onclickeventField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class htmlentity : entity {
        
        private string urlField;
        
        private string onmessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("on-message")]
        public string onmessage {
            get {
                return this.onmessageField;
            }
            set {
                this.onmessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class canvasentity : entity {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class characterentity : entity {
        
        private string meshnameField;
        
        private string[] meshresourceField;
        
        private position meshoffsetField;
        
        private rotation meshrotationField;
        
        private position labeloffsetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mesh-name")]
        public string meshname {
            get {
                return this.meshnameField;
            }
            set {
                this.meshnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mesh-resource")]
        public string[] meshresource {
            get {
                return this.meshresourceField;
            }
            set {
                this.meshresourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mesh-offset")]
        public position meshoffset {
            get {
                return this.meshoffsetField;
            }
            set {
                this.meshoffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mesh-rotation")]
        public rotation meshrotation {
            get {
                return this.meshrotationField;
            }
            set {
                this.meshrotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("label-offset")]
        public position labeloffset {
            get {
                return this.labeloffsetField;
            }
            set {
                this.labeloffsetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class archmeshentity : entity {
        
        private string colorField;
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class prismmeshentity : entity {
        
        private string colorField;
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class tetrahedronmeshentity : entity {
        
        private string colorField;
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class rectangularpyramidmeshentity : entity {
        
        private string colorField;
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class conemeshentity : entity {
        
        private string colorField;
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class torusmeshentity : entity {
        
        private string colorField;
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class planemeshentity : entity {
        
        private string colorField;
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class cylindermeshentity : entity {
        
        private string colorField;
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class capsulemeshentity : entity {
        
        private string colorField;
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class spheremeshentity : entity {
        
        private string colorField;
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class cubemeshentity : entity {
        
        private string colorField;
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class meshentity : entity {
        
        private string meshnameField;
        
        private string[] meshresourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mesh-name")]
        public string meshname {
            get {
                return this.meshnameField;
            }
            set {
                this.meshnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mesh-resource")]
        public string[] meshresource {
            get {
                return this.meshresourceField;
            }
            set {
                this.meshresourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class audioentity : entity {
        
        private string audiofileField;
        
        private bool autoplayField;
        
        private bool loopField;
        
        private int priorityField;
        
        private float volumeField;
        
        private float pitchField;
        
        private float stereopanField;
        
        public audioentity() {
            this.autoplayField = true;
            this.loopField = true;
            this.priorityField = 0;
            this.volumeField = ((float)(1F));
            this.pitchField = ((float)(0F));
            this.stereopanField = ((float)(0F));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("audio-file")]
        public string audiofile {
            get {
                return this.audiofileField;
            }
            set {
                this.audiofileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("auto-play")]
        public bool autoplay {
            get {
                return this.autoplayField;
            }
            set {
                this.autoplayField = value;
            }
        }
        
        /// <remarks/>
        public bool loop {
            get {
                return this.loopField;
            }
            set {
                this.loopField = value;
            }
        }
        
        /// <remarks/>
        public int priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public float volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        public float pitch {
            get {
                return this.pitchField;
            }
            set {
                this.pitchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stereo-pan")]
        public float stereopan {
            get {
                return this.stereopanField;
            }
            set {
                this.stereopanField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class containerentity : entity {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="lite-fog-settings", Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class litefogsettings {
        
        private bool fogenabledField;
        
        private string colorField;
        
        private float densityField;
        
        public litefogsettings() {
            this.fogenabledField = false;
            this.colorField = "gray";
            this.densityField = ((float)(0.5F));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("fog-enabled")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool fogenabled {
            get {
                return this.fogenabledField;
            }
            set {
                this.fogenabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("gray")]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.5")]
        public float density {
            get {
                return this.densityField;
            }
            set {
                this.densityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="effects-settings", Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class effectssettings {
        
        private litefogsettings litefogField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lite-fog")]
        public litefogsettings litefog {
            get {
                return this.litefogField;
            }
            set {
                this.litefogField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class liteproceduralsky {
        
        private string sunentitytagField;
        
        private bool daynightcycleenabledField;
        
        private bool groundenabledField;
        
        private string groundcolorField;
        
        private float groundheightField;
        
        private float groundfadeamountField;
        
        private float horizonskyblendField;
        
        private string dayhorizoncolorField;
        
        private string dayskycolorField;
        
        private string nighthorizoncolorField;
        
        private string nightskycolorField;
        
        private float horizonsaturationamountField;
        
        private float horizonsaturationfalloffField;
        
        private bool sunenabledField;
        
        private float sundiameterField;
        
        private string sunhorizoncolorField;
        
        private string sunzenithcolorField;
        
        private bool sunskylightingenabledField;
        
        private float skylightingfalloffamountField;
        
        private float skylightingfalloffintensityField;
        
        private float sunsetintensityField;
        
        private float sunsetradialfalloffField;
        
        private float sunsethorizontalfalloffField;
        
        private float sunsetverticalfalloffField;
        
        private bool moonenabledField;
        
        private float moondiameterField;
        
        private string mooncolorField;
        
        private float moonfalloffamountField;
        
        private bool starsenabledField;
        
        private float starsbrightnessField;
        
        private float starsdaytimebrightnessField;
        
        private float starshorizonfalloffField;
        
        private float starssaturationField;
        
        private bool proceduralstarsenabledField;
        
        private float proceduralstarssharpnessField;
        
        private float proceduralstarsamountField;
        
        private bool starstextureenabledField;
        
        private string startextureuriField;
        
        private string startintField;
        
        private float starscaleField;
        
        private float starrotationspeedField;
        
        private bool cloudsenabledField;
        
        private string cloudstextureuriField;
        
        private float cloudsscalexField;
        
        private float cloudsscaleyField;
        
        private float cloudsspeedxField;
        
        private float cloudsspeedyField;
        
        private float cloudinessField;
        
        private float cloudsopacityField;
        
        private float cloudssharpnessField;
        
        private float cloudsshadingintensityField;
        
        private float cloudszenithfalloffField;
        
        private int cloudsiterationsField;
        
        private float cloudsgainField;
        
        private int cloudslacunarityField;
        
        private string cloudsdaycolorField;
        
        private string cloudsnightcolorField;
        
        public liteproceduralsky() {
            this.daynightcycleenabledField = true;
            this.groundenabledField = true;
            this.groundcolorField = "#07070700";
            this.groundheightField = ((float)(-0.02F));
            this.groundfadeamountField = ((float)(0.02F));
            this.horizonskyblendField = ((float)(0.579F));
            this.dayhorizoncolorField = "#448bc5ff";
            this.dayskycolorField = "#08124100";
            this.nighthorizoncolorField = "#07050d00";
            this.nightskycolorField = "00000000";
            this.horizonsaturationamountField = ((float)(0.894F));
            this.horizonsaturationfalloffField = ((float)(4.45F));
            this.sunenabledField = true;
            this.sundiameterField = ((float)(2F));
            this.sunhorizoncolorField = "color(155 72 33 0)";
            this.sunzenithcolorField = "color(158 129 58 0)";
            this.sunskylightingenabledField = true;
            this.skylightingfalloffamountField = ((float)(10F));
            this.skylightingfalloffintensityField = ((float)(18F));
            this.sunsetintensityField = ((float)(0.039F));
            this.sunsetradialfalloffField = ((float)(0.1F));
            this.sunsethorizontalfalloffField = ((float)(0.6F));
            this.sunsetverticalfalloffField = ((float)(0.5F));
            this.moonenabledField = true;
            this.moondiameterField = ((float)(2F));
            this.mooncolorField = "#abb9bf00";
            this.moonfalloffamountField = ((float)(60F));
            this.starsenabledField = true;
            this.starsbrightnessField = ((float)(0.85F));
            this.starsdaytimebrightnessField = ((float)(0.1F));
            this.starshorizonfalloffField = ((float)(0F));
            this.starssaturationField = ((float)(0.3F));
            this.proceduralstarsenabledField = true;
            this.proceduralstarssharpnessField = ((float)(1F));
            this.proceduralstarsamountField = ((float)(1F));
            this.starstextureenabledField = true;
            this.startintField = "#ffffff00";
            this.starscaleField = ((float)(0.5F));
            this.starrotationspeedField = ((float)(0.25F));
            this.cloudsenabledField = true;
            this.cloudsscalexField = ((float)(2F));
            this.cloudsscaleyField = ((float)(1F));
            this.cloudsspeedxField = ((float)(0.2F));
            this.cloudsspeedyField = ((float)(0.3F));
            this.cloudinessField = ((float)(0.279F));
            this.cloudsopacityField = ((float)(1F));
            this.cloudssharpnessField = ((float)(0.8F));
            this.cloudsshadingintensityField = ((float)(0.8F));
            this.cloudszenithfalloffField = ((float)(0.339F));
            this.cloudsiterationsField = 3;
            this.cloudsgainField = ((float)(0.5F));
            this.cloudslacunarityField = 2;
            this.cloudsdaycolorField = "#d7dde7";
            this.cloudsnightcolorField = "#120c0f";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sun-entity-tag")]
        public string sunentitytag {
            get {
                return this.sunentitytagField;
            }
            set {
                this.sunentitytagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("day-night-cycle-enabled")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool daynightcycleenabled {
            get {
                return this.daynightcycleenabledField;
            }
            set {
                this.daynightcycleenabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ground-enabled")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool groundenabled {
            get {
                return this.groundenabledField;
            }
            set {
                this.groundenabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ground-color")]
        [System.ComponentModel.DefaultValueAttribute("#07070700")]
        public string groundcolor {
            get {
                return this.groundcolorField;
            }
            set {
                this.groundcolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ground-height")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "-0.02")]
        public float groundheight {
            get {
                return this.groundheightField;
            }
            set {
                this.groundheightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ground-fade-amount")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.02")]
        public float groundfadeamount {
            get {
                return this.groundfadeamountField;
            }
            set {
                this.groundfadeamountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("horizon-sky-blend")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.579")]
        public float horizonskyblend {
            get {
                return this.horizonskyblendField;
            }
            set {
                this.horizonskyblendField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("day-horizon-color")]
        [System.ComponentModel.DefaultValueAttribute("#448bc5ff")]
        public string dayhorizoncolor {
            get {
                return this.dayhorizoncolorField;
            }
            set {
                this.dayhorizoncolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("day-sky-color")]
        [System.ComponentModel.DefaultValueAttribute("#08124100")]
        public string dayskycolor {
            get {
                return this.dayskycolorField;
            }
            set {
                this.dayskycolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("night-horizon-color")]
        [System.ComponentModel.DefaultValueAttribute("#07050d00")]
        public string nighthorizoncolor {
            get {
                return this.nighthorizoncolorField;
            }
            set {
                this.nighthorizoncolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("night-sky-color")]
        [System.ComponentModel.DefaultValueAttribute("03010300")]
        public string nightskycolor {
            get {
                return this.nightskycolorField;
            }
            set {
                this.nightskycolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("horizon-saturation-amount")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.894")]
        public float horizonsaturationamount {
            get {
                return this.horizonsaturationamountField;
            }
            set {
                this.horizonsaturationamountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("horizon-saturation-falloff")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "4.45")]
        public float horizonsaturationfalloff {
            get {
                return this.horizonsaturationfalloffField;
            }
            set {
                this.horizonsaturationfalloffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sun-enabled")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool sunenabled {
            get {
                return this.sunenabledField;
            }
            set {
                this.sunenabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sun-diameter")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "2")]
        public float sundiameter {
            get {
                return this.sundiameterField;
            }
            set {
                this.sundiameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sun-horizon-color")]
        [System.ComponentModel.DefaultValueAttribute("color(155 72 33 0)")]
        public string sunhorizoncolor {
            get {
                return this.sunhorizoncolorField;
            }
            set {
                this.sunhorizoncolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sun-zenith-color")]
        [System.ComponentModel.DefaultValueAttribute("color(158 129 58 0)")]
        public string sunzenithcolor {
            get {
                return this.sunzenithcolorField;
            }
            set {
                this.sunzenithcolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sun-sky-lighting-enabled")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool sunskylightingenabled {
            get {
                return this.sunskylightingenabledField;
            }
            set {
                this.sunskylightingenabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sky-lighting-falloff-amount")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "10")]
        public float skylightingfalloffamount {
            get {
                return this.skylightingfalloffamountField;
            }
            set {
                this.skylightingfalloffamountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sky-lighting-falloff-intensity")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float skylightingfalloffintensity {
            get {
                return this.skylightingfalloffintensityField;
            }
            set {
                this.skylightingfalloffintensityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sunset-intensity")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.3")]
        public float sunsetintensity {
            get {
                return this.sunsetintensityField;
            }
            set {
                this.sunsetintensityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sunset-radial-falloff")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.1")]
        public float sunsetradialfalloff {
            get {
                return this.sunsetradialfalloffField;
            }
            set {
                this.sunsetradialfalloffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sunset-horizontal-falloff")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.6")]
        public float sunsethorizontalfalloff {
            get {
                return this.sunsethorizontalfalloffField;
            }
            set {
                this.sunsethorizontalfalloffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sunset-vertical-falloff")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.5")]
        public float sunsetverticalfalloff {
            get {
                return this.sunsetverticalfalloffField;
            }
            set {
                this.sunsetverticalfalloffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("moon-enabled")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool moonenabled {
            get {
                return this.moonenabledField;
            }
            set {
                this.moonenabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("moon-diameter")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "2")]
        public float moondiameter {
            get {
                return this.moondiameterField;
            }
            set {
                this.moondiameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("moon-color")]
        [System.ComponentModel.DefaultValueAttribute("#abb9bf00")]
        public string mooncolor {
            get {
                return this.mooncolorField;
            }
            set {
                this.mooncolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("moon-falloff-amount")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "60")]
        public float moonfalloffamount {
            get {
                return this.moonfalloffamountField;
            }
            set {
                this.moonfalloffamountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("stars-enabled")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool starsenabled {
            get {
                return this.starsenabledField;
            }
            set {
                this.starsenabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("stars-brightness")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.85")]
        public float starsbrightness {
            get {
                return this.starsbrightnessField;
            }
            set {
                this.starsbrightnessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("stars-daytime-brightness")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.1")]
        public float starsdaytimebrightness {
            get {
                return this.starsdaytimebrightnessField;
            }
            set {
                this.starsdaytimebrightnessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("stars-horizon-falloff")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float starshorizonfalloff {
            get {
                return this.starshorizonfalloffField;
            }
            set {
                this.starshorizonfalloffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("stars-saturation")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.3")]
        public float starssaturation {
            get {
                return this.starssaturationField;
            }
            set {
                this.starssaturationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("procedural-stars-enabled")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool proceduralstarsenabled {
            get {
                return this.proceduralstarsenabledField;
            }
            set {
                this.proceduralstarsenabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("procedural-stars-sharpness")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float proceduralstarssharpness {
            get {
                return this.proceduralstarssharpnessField;
            }
            set {
                this.proceduralstarssharpnessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("procedural-stars-amount")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float proceduralstarsamount {
            get {
                return this.proceduralstarsamountField;
            }
            set {
                this.proceduralstarsamountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("stars-texture-enabled")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool starstextureenabled {
            get {
                return this.starstextureenabledField;
            }
            set {
                this.starstextureenabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("star-texture-uri")]
        public string startextureuri {
            get {
                return this.startextureuriField;
            }
            set {
                this.startextureuriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("star-tint")]
        [System.ComponentModel.DefaultValueAttribute("#ffffff00")]
        public string startint {
            get {
                return this.startintField;
            }
            set {
                this.startintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("star-scale")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.5")]
        public float starscale {
            get {
                return this.starscaleField;
            }
            set {
                this.starscaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("star-rotation-speed")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.25")]
        public float starrotationspeed {
            get {
                return this.starrotationspeedField;
            }
            set {
                this.starrotationspeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-enabled")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool cloudsenabled {
            get {
                return this.cloudsenabledField;
            }
            set {
                this.cloudsenabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-texture-uri")]
        public string cloudstextureuri {
            get {
                return this.cloudstextureuriField;
            }
            set {
                this.cloudstextureuriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-scale-x")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "2")]
        public float cloudsscalex {
            get {
                return this.cloudsscalexField;
            }
            set {
                this.cloudsscalexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-scale-y")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float cloudsscaley {
            get {
                return this.cloudsscaleyField;
            }
            set {
                this.cloudsscaleyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-speed-x")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.2")]
        public float cloudsspeedx {
            get {
                return this.cloudsspeedxField;
            }
            set {
                this.cloudsspeedxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-speed-y")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.3")]
        public float cloudsspeedy {
            get {
                return this.cloudsspeedyField;
            }
            set {
                this.cloudsspeedyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.279")]
        public float cloudiness {
            get {
                return this.cloudinessField;
            }
            set {
                this.cloudinessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-opacity")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float cloudsopacity {
            get {
                return this.cloudsopacityField;
            }
            set {
                this.cloudsopacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-sharpness")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.8")]
        public float cloudssharpness {
            get {
                return this.cloudssharpnessField;
            }
            set {
                this.cloudssharpnessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-shading-intensity")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.8")]
        public float cloudsshadingintensity {
            get {
                return this.cloudsshadingintensityField;
            }
            set {
                this.cloudsshadingintensityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-zenith-falloff")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.339")]
        public float cloudszenithfalloff {
            get {
                return this.cloudszenithfalloffField;
            }
            set {
                this.cloudszenithfalloffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-iterations")]
        [System.ComponentModel.DefaultValueAttribute(3)]
        public int cloudsiterations {
            get {
                return this.cloudsiterationsField;
            }
            set {
                this.cloudsiterationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-gain")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.5")]
        public float cloudsgain {
            get {
                return this.cloudsgainField;
            }
            set {
                this.cloudsgainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-lacunarity")]
        [System.ComponentModel.DefaultValueAttribute(2)]
        public int cloudslacunarity {
            get {
                return this.cloudslacunarityField;
            }
            set {
                this.cloudslacunarityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-day-color")]
        [System.ComponentModel.DefaultValueAttribute("#d7dde7")]
        public string cloudsdaycolor {
            get {
                return this.cloudsdaycolorField;
            }
            set {
                this.cloudsdaycolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("clouds-night-color")]
        [System.ComponentModel.DefaultValueAttribute("#7d616f")]
        public string cloudsnightcolor {
            get {
                return this.cloudsnightcolorField;
            }
            set {
                this.cloudsnightcolorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class background {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("color", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("lite-procedural-sky", typeof(liteproceduralsky))]
        [System.Xml.Serialization.XmlElementAttribute("panorama", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        color,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("lite-procedural-sky")]
        liteproceduralsky,
        
        /// <remarks/>
        panorama,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class synchronizationservice {
        
        private string typeField;
        
        private string addressField;
        
        private string idField;
        
        private string sessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class controlflags {
        
        private string leftvrpointerField;
        
        private string rightvrpointerField;
        
        private bool leftvrpokerField;
        
        private bool leftvrpokerFieldSpecified;
        
        private bool rightvrpokerField;
        
        private bool rightvrpokerFieldSpecified;
        
        private bool lefthandinteractionField;
        
        private bool lefthandinteractionFieldSpecified;
        
        private bool righthandinteractionField;
        
        private bool righthandinteractionFieldSpecified;
        
        private string turnlocomotionField;
        
        private bool joystickmotionField;
        
        private bool joystickmotionFieldSpecified;
        
        private bool leftgrabmoveField;
        
        private bool leftgrabmoveFieldSpecified;
        
        private bool rightgrabmoveField;
        
        private bool rightgrabmoveFieldSpecified;
        
        private bool twohandedgrabmoveField;
        
        private bool twohandedgrabmoveFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("left-vr-pointer")]
        public string leftvrpointer {
            get {
                return this.leftvrpointerField;
            }
            set {
                this.leftvrpointerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("right-vr-pointer")]
        public string rightvrpointer {
            get {
                return this.rightvrpointerField;
            }
            set {
                this.rightvrpointerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("left-vr-poker")]
        public bool leftvrpoker {
            get {
                return this.leftvrpokerField;
            }
            set {
                this.leftvrpokerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool leftvrpokerSpecified {
            get {
                return this.leftvrpokerFieldSpecified;
            }
            set {
                this.leftvrpokerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("right-vr-poker")]
        public bool rightvrpoker {
            get {
                return this.rightvrpokerField;
            }
            set {
                this.rightvrpokerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rightvrpokerSpecified {
            get {
                return this.rightvrpokerFieldSpecified;
            }
            set {
                this.rightvrpokerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("left-hand-interaction")]
        public bool lefthandinteraction {
            get {
                return this.lefthandinteractionField;
            }
            set {
                this.lefthandinteractionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lefthandinteractionSpecified {
            get {
                return this.lefthandinteractionFieldSpecified;
            }
            set {
                this.lefthandinteractionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("right-hand-interaction")]
        public bool righthandinteraction {
            get {
                return this.righthandinteractionField;
            }
            set {
                this.righthandinteractionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool righthandinteractionSpecified {
            get {
                return this.righthandinteractionFieldSpecified;
            }
            set {
                this.righthandinteractionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("turn-locomotion")]
        public string turnlocomotion {
            get {
                return this.turnlocomotionField;
            }
            set {
                this.turnlocomotionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("joystick-motion")]
        public bool joystickmotion {
            get {
                return this.joystickmotionField;
            }
            set {
                this.joystickmotionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool joystickmotionSpecified {
            get {
                return this.joystickmotionFieldSpecified;
            }
            set {
                this.joystickmotionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("left-grab-move")]
        public bool leftgrabmove {
            get {
                return this.leftgrabmoveField;
            }
            set {
                this.leftgrabmoveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool leftgrabmoveSpecified {
            get {
                return this.leftgrabmoveFieldSpecified;
            }
            set {
                this.leftgrabmoveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("right-grab-move")]
        public bool rightgrabmove {
            get {
                return this.rightgrabmoveField;
            }
            set {
                this.rightgrabmoveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rightgrabmoveSpecified {
            get {
                return this.rightgrabmoveFieldSpecified;
            }
            set {
                this.rightgrabmoveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("two-handed-grab-move")]
        public bool twohandedgrabmove {
            get {
                return this.twohandedgrabmoveField;
            }
            set {
                this.twohandedgrabmoveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool twohandedgrabmoveSpecified {
            get {
                return this.twohandedgrabmoveFieldSpecified;
            }
            set {
                this.twohandedgrabmoveFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fivesqd.com/schemas/veml/2.3")]
    public partial class vemlEnvironment {
        
        private background backgroundField;
        
        private effectssettings effectsField;
        
        private entity[] entityField;
        
        /// <remarks/>
        public background background {
            get {
                return this.backgroundField;
            }
            set {
                this.backgroundField = value;
            }
        }
        
        /// <remarks/>
        public effectssettings effects {
            get {
                return this.effectsField;
            }
            set {
                this.effectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entity")]
        public entity[] entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
    }
}